/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/inventory/v1/properties": {
    /** Get the list of properties.<br>You need to be authorized (no particular scope required) */
    get: operations["InventoryPropertiesGet"];
    /** Use this call to create a new property.<br>You must have at least one of these scopes: 'properties.create, setup.manage'. */
    post: operations["InventoryPropertiesPost"];
  };
  "/inventory/v1/properties/$count": {
    /** Return total count of properties<br>You need to be authorized (no particular scope required) */
    get: operations["InventoryProperties$countGet"];
  };
  "/inventory/v1/properties/{id}": {
    /** Get a property by id.<br>You need to be authorized (no particular scope required) */
    get: operations["InventoryPropertiesByIdGet"];
    /** Check if a property exists by id.<br>You need to be authorized (no particular scope required) */
    head: operations["InventoryPropertiesByIdHead"];
    /**
     * Here's a list of allowed operations:
     * - Replace Name
     * - Add, replace and remove Description
     * - Replace CompanyName
     * - Add, replace and remove ManagingDirectors
     * - Replace CommercialRegisterEntry
     * - Replace TaxId
     * - Replace Location
     * - Add, replace and remove BankAccount
     * - Replace PaymentTerms
     * - Set IsTemplate<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.
     */
    patch: operations["InventoryPropertiesByIdPatch"];
  };
  "/inventory/v1/property-actions/{id}/clone": {
    /**
     * Use this call to clone a specific property.
     * This operation creates a new property with inventory and rate plans from the specified property.<br>You must have at least one of these scopes: 'properties.create, setup.manage'.
     */
    post: operations["InventoryProperty-actionsByIdClonePost"];
  };
  "/inventory/v1/property-actions/{id}/archive": {
    /**
     * Use this endpoint to archive an existing live property
     * This operation set the IsArchived flag to true<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.
     */
    put: operations["InventoryProperty-actionsByIdArchivePut"];
  };
  "/inventory/v1/property-actions/{id}/set-live": {
    /**
     * Use this endpoint to move an existing test property to live
     * This operation changes the property status to 'Live'<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.
     */
    put: operations["InventoryProperty-actionsByIdSet-livePut"];
  };
  "/inventory/v1/property-actions/{id}/reset": {
    /**
     * Use this endpoint to delete all transactional data related to some test property
     * This operation deletes all transactional data related to the specified property. The property must be in 'Test' status.<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.
     */
    put: operations["InventoryProperty-actionsByIdResetPut"];
  };
  "/inventory/v1/types/countries": {
    /** Returns a list of ISO country codes that could be used to create properties.<br>You need to be authorized (no particular scope required) */
    get: operations["InventoryTypesCountriesGet"];
  };
  "/inventory/v1/units/{id}": {
    /** Get a unit by id.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'. */
    get: operations["InventoryUnitsByIdGet"];
    /** Use this call to delete a unit.<br>You must have at least one of these scopes: 'units.delete, setup.manage'. */
    delete: operations["InventoryUnitsByIdDelete"];
    /** Check if a unit exists by id.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'. */
    head: operations["InventoryUnitsByIdHead"];
    /**
     * Here's a list of allowed operations:
     * - Set unit condition
     * - Set unit description
     * - Set unit name
     * - Set unit unitGroupId
     * - Set unit maxPersons
     * - Add unit attribute
     * - Remove unit attribute<br>You must have at least one of these scopes: 'units.manage, setup.manage'.
     */
    patch: operations["InventoryUnitsByIdPatch"];
  };
  "/inventory/v1/units": {
    /** Get the list of units.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'. */
    get: operations["InventoryUnitsGet"];
    /** Use this call to create a new unit.<br>You must have at least one of these scopes: 'units.create, setup.manage'. */
    post: operations["InventoryUnitsPost"];
    /**
     * Here's a list of allowed operations:
     * - Set unit condition
     * - Set unit description
     * - Set unit name
     * - Set unit unitGroupId
     * - Set unit maxPersons
     * - Add unit attribute
     * - Remove unit attribute<br>You must have at least one of these scopes: 'units.manage, setup.manage'.
     */
    patch: operations["InventoryUnitsPatch"];
  };
  "/inventory/v1/units/$count": {
    /** Returns number of units matching the filter criteria<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'. */
    get: operations["InventoryUnits$countGet"];
  };
  "/inventory/v1/units/bulk": {
    /** Use this call to create multiple units, following a naming rule.<br>You must have at least one of these scopes: 'units.create, setup.manage'. */
    post: operations["InventoryUnitsBulkPost"];
  };
  "/inventory/v1/unit-attributes/{id}": {
    /** Get unit attribute by id<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'. */
    get: operations["InventoryUnit-attributesByIdGet"];
    /** Deletes unit attribute<br>You must have at least one of these scopes: 'unitattributes.delete, setup.manage'. */
    delete: operations["InventoryUnit-attributesByIdDelete"];
    /** Check if a unit attribute exists<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'. */
    head: operations["InventoryUnit-attributesByIdHead"];
    /**
     * Here's a list of allowed operations:
     * - Replace / Remove Description<br>You must have at least one of these scopes: 'unitattributes.manage, setup.manage'.
     */
    patch: operations["InventoryUnit-attributesByIdPatch"];
  };
  "/inventory/v1/unit-attributes": {
    /** Get unit attribute list<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'. */
    get: operations["InventoryUnit-attributesGet"];
    /** Use this call to create a new unit attribute.<br>You must have at least one of these scopes: 'unitattributes.create, setup.manage'. */
    post: operations["InventoryUnit-attributesPost"];
  };
  "/inventory/v1/unit-groups": {
    /** Get the list of unit groups.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'. */
    get: operations["InventoryUnit-groupsGet"];
    /** Use this call to create a new unit group.<br>You must have at least one of these scopes: 'unitgroups.create, setup.manage'. */
    post: operations["InventoryUnit-groupsPost"];
  };
  "/inventory/v1/unit-groups/$count": {
    /** Returns number of unit groups matching the filter criteria<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'. */
    get: operations["InventoryUnit-groups$countGet"];
  };
  "/inventory/v1/unit-groups/{id}": {
    /** Get a unit group by id.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'. */
    get: operations["InventoryUnit-groupsByIdGet"];
    /** Use this call to modify a unit group.<br>You must have at least one of these scopes: 'unitgroups.manage, setup.manage'. */
    put: operations["InventoryUnit-groupsByIdPut"];
    /** Use this call to delete a unit group.<br>You must have at least one of these scopes: 'unitgroups.delete, setup.manage'. */
    delete: operations["InventoryUnit-groupsByIdDelete"];
    /** Check if a unit group exists by id.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'. */
    head: operations["InventoryUnit-groupsByIdHead"];
  };
}

export interface definitions {
  "ActionModel[PropertyAction,NotAllowedPropertyActionReason]": {
    action: "Delete" | "Archive" | "SetLive" | "Reset";
    isAllowed: boolean;
    reasons?: definitions["ActionReasonModel[NotAllowedPropertyActionReason]"][];
  };
  "ActionReasonModel[NotAllowedPropertyActionReason]": {
    code:
      | "DeleteNotAllowedForPropertyNotInStatusTest"
      | "ArchiveNotAllowedForPropertyNotInStatusLive"
      | "ArchiveNotAllowedForPropertyWhichIsAlreadyArchived"
      | "SetToLiveNotAllowedForPropertyNotInStatusTest"
      | "SetToLiveNotAllowedForPropertyInNonLiveAccount"
      | "ResetNotAllowedForPropertyNotInStatusTest";
    message: string;
  };
  AddressModel: {
    addressLine1: string;
    addressLine2?: string;
    postalCode: string;
    city: string;
    regionCode?: string;
    countryCode: string;
  };
  BankAccountModel: {
    iban?: string;
    bic?: string;
    bank?: string;
  };
  BulkCreateUnitsModel: {
    units: definitions["CreateUnitModel"][];
  };
  BulkUnitsCreatedModel: {
    /** The unit ids */
    ids: string[];
  };
  ConnectedUnitGroupModel: {
    /** The unit group id */
    id: string;
    /** The name for the unit group */
    name: string;
    /** The description for the unit group */
    description: string;
    /** The number of units taken from this connected unit group */
    memberCount: number;
    /** Maximum number of persons for the unit group */
    maxPersons?: number;
  };
  ConnectedUnitModel: {
    /** The unit id */
    id: string;
    /** The name for the unit */
    name: string;
    /** The description for the unit */
    description: string;
    /** The unit group id */
    unitGroupId: string;
    /** The current status of the unit */
    condition: "Clean" | "CleanToBeInspected" | "Dirty";
    /** Maximum number of persons for the unit */
    maxPersons: number;
  };
  CountModel: {
    count: number;
  };
  CountryListModel: {
    /** List of ISO country codes. */
    countryCodes: string[];
  };
  CreateAddressModel: {
    addressLine1: string;
    addressLine2?: string;
    postalCode: string;
    city: string;
    /** The ISO 3166-2 code */
    regionCode?: string;
    /** The country code, in ISO 3166-1 alpha-2 code */
    countryCode: string;
  };
  CreateConnectedUnitGroupModel: {
    /** The connected unit group id */
    unitGroupId: string;
    /** The number of units for this connected unit group */
    memberCount: number;
  };
  CreateConnectedUnitModel: {
    /** The connected unit id */
    unitId: string;
  };
  CreatePropertyModel: {
    /** The code for the property that can be shown in reports and table views */
    code: string;
    /** The name for the property */
    name: { [key: string]: string };
    /** The legal name of the company running the property. */
    companyName: string;
    /** The managing director(s) of the company, as they should appear on invoices */
    managingDirectors?: string;
    /** The entry in the Commercial Reigster of the company running the property, as it should appear on invoices */
    commercialRegisterEntry: string;
    /** The Tax-ID of the company running the property, as it should appear on invoices */
    taxId: string;
    /** The description for the property */
    description?: { [key: string]: string };
    location: definitions["CreateAddressModel"];
    bankAccount?: definitions["BankAccountModel"];
    /** The payment terms used for all rate plans */
    paymentTerms: { [key: string]: string };
    /**
     * The time zone name of the property from the IANA Time Zone Database.
     * (see: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
     */
    timeZone: string;
    /** The default check-in time<br />A time (without fractional second part) as defined in the <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a> */
    defaultCheckInTime: string;
    /** The default check-out time<br />A time (without fractional second part) as defined in the <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a> */
    defaultCheckOutTime: string;
    /** The currency a property works with. */
    currencyCode: string;
  };
  CreateUnitAttributeDefinitionModel: {
    /** The name of the unit attribute */
    name: string;
    /** The description of the unit attribute */
    description?: string;
  };
  CreateUnitAttributeModel: {
    /** Id of unit attribute */
    id: string;
  };
  CreateUnitGroupModel: {
    /** The code for the unit group that can be shown in reports and table views */
    code: string;
    /** The id of the property where unit group will be created */
    propertyId: string;
    /** The name for the unit group */
    name: { [key: string]: string };
    /** The description for the unit group */
    description: { [key: string]: string };
    /** Maximum number of persons for the unit group */
    maxPersons: number;
    /**
     * The unit group rank
     * Restrictions:
     * - Should be greater or equal to one
     */
    rank?: number;
    /** The unit group type */
    type?: "BedRoom" | "MeetingRoom" | "EventSpace" | "ParkingLot";
    /** The list of connected unit groups this unit group is composed of */
    connectedUnitGroups?: definitions["CreateConnectedUnitGroupModel"][];
  };
  CreateUnitModel: {
    /** The id of the property where the unit will be created */
    propertyId: string;
    /** The name for the unit */
    name: string;
    /** The description for the unit */
    description: { [key: string]: string };
    /** The id of the unit group */
    unitGroupId?: string;
    /** Maximum number of persons for the unit */
    maxPersons: number;
    /** Condition of the unit */
    condition?: "Clean" | "CleanToBeInspected" | "Dirty";
    /** Collection of user defined attributes of unit */
    attributes?: definitions["CreateUnitAttributeModel"][];
    /** The list of units this unit is composed of */
    connectedUnits?: definitions["CreateConnectedUnitModel"][];
  };
  EmbeddedPropertyModel: {
    /** The property id */
    id: string;
    /** The code for the property that can be shown in reports and table views */
    code?: string;
    /** The name for the property */
    name?: string;
    /** The description for the property */
    description?: string;
  };
  EmbeddedUnitGroupModel: {
    /** The unit group id */
    id: string;
    /** The code for the unit group that can be shown in reports and table views */
    code?: string;
    /** The name for the unit group */
    name?: string;
    /** The description for the unit group */
    description?: string;
    /** The unit group type */
    type?: "BedRoom" | "MeetingRoom" | "EventSpace" | "ParkingLot" | "Other";
  };
  EmbeddedUnitModel: {
    /** The unit id */
    id: string;
    /** The name for the unit */
    name?: string;
    /** The description for the unit */
    description?: string;
    /** The unit group id */
    unitGroupId?: string;
  };
  MessageItemCollection: {
    messages?: string[];
  };
  Operation: {
    value?: { [key: string]: unknown };
    path?: string;
    op?: string;
    from?: string;
  };
  PropertyCreatedModel: {
    /** The property id */
    id: string;
  };
  PropertyItemModel: {
    /** The property id */
    id: string;
    /** The code for the property that can be shown in reports and table views */
    code: string;
    /** The id of the property used as a template while creating the property */
    propertyTemplateId?: string;
    /** Whether the property can be used as a template for other properties */
    isTemplate: boolean;
    /** The name for the property */
    name: string;
    /** The description for the property */
    description?: string;
    /** The legal name of the company running the property. */
    companyName: string;
    /** The managing director(s) of the company, as they should appear on invoices */
    managingDirectors?: string;
    /** The entry in the Commercial Register of the company running the property, as it should appear on invoices */
    commercialRegisterEntry: string;
    /** The Tax-ID of the company running the property, as it should appear on invoices */
    taxId: string;
    location: definitions["AddressModel"];
    bankAccount?: definitions["BankAccountModel"];
    /** The payment terms used for all rate plans */
    paymentTerms: { [key: string]: string };
    /**
     * The time zone name of the property from the IANA Time Zone Database.
     * (see: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
     */
    timeZone: string;
    /** The currency a property works with. */
    currencyCode: string;
    /** Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a> */
    created: string;
    /** The status of the property */
    status: "Test" | "Live";
    /** Is the property archived */
    isArchived: boolean;
    /** The list of actions for this property */
    actions?: definitions["ActionModel[PropertyAction,NotAllowedPropertyActionReason]"][];
  };
  PropertyListModel: {
    /** List of properties */
    properties: definitions["PropertyItemModel"][];
    /** Total count of items */
    count: number;
  };
  /** With this request you can create a new property */
  PropertyModel: {
    /** The property id */
    id: string;
    /** The code for the property that can be shown in reports and table views */
    code: string;
    /** The id of the property used as a template while creating the property */
    propertyTemplateId?: string;
    /** Whether the property can be used as a template for other properties */
    isTemplate: boolean;
    /** The name for the property */
    name: { [key: string]: string };
    /** The description for the property */
    description?: { [key: string]: string };
    /** The legal name of the company running the property. */
    companyName: string;
    /** The managing director(s) of the company, as they should appear on invoices */
    managingDirectors?: string;
    /** The entry in the Commercial Register of the company running the property, as it should appear on invoices */
    commercialRegisterEntry: string;
    /** The Tax-ID of the company running the property, as it should appear on invoices */
    taxId: string;
    location: definitions["AddressModel"];
    bankAccount?: definitions["BankAccountModel"];
    /** The payment terms used for all rate plans */
    paymentTerms: { [key: string]: string };
    /**
     * The time zone name of the property from the IANA Time Zone Database.
     * (see: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
     */
    timeZone: string;
    /** The currency a property works with. */
    currencyCode: string;
    /** Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a> */
    created: string;
    /** The status of the property */
    status: "Test" | "Live";
    /** Is the property archived */
    isArchived: boolean;
    /** The list of actions for this property */
    actions?: definitions["ActionModel[PropertyAction,NotAllowedPropertyActionReason]"][];
  };
  ReplaceConnectedUnitGroupModel: {
    /** The connected unit group id */
    unitGroupId: string;
    /** The number of units for this connected unit group */
    memberCount: number;
  };
  ReplaceUnitGroupModel: {
    /** The name for the unit group */
    name: { [key: string]: string };
    /** The description for the unit group */
    description: { [key: string]: string };
    /**
     * Maximum number of persons for the unit group.
     * If this value is increased, the surcharges for the related rate plans must be specified in order for the rate plans to be sellable for the new possible occupancies.
     */
    maxPersons?: number;
    /**
     * The unit group rank
     * Restrictions:
     * - Should be greater or equal to one
     */
    rank?: number;
    /** The list of connected unit groups this unit group is composed of */
    connectedUnitGroups?: definitions["ReplaceConnectedUnitGroupModel"][];
  };
  UnitAttributeDefinitionCreatedModel: {
    /** The unit attribute id */
    id: string;
  };
  UnitAttributeDefinitionListModel: {
    /** List of unit attributes */
    unitAttributes: definitions["UnitAttributeDefinitionModel"][];
    /** Total count of items */
    count: number;
  };
  UnitAttributeDefinitionModel: {
    /** The id of the unit attribute */
    id: string;
    /** The name of the unit attribute */
    name: string;
    /** The description of the unit attribute */
    description?: string;
  };
  UnitAttributeModel: {
    /** Id of unit attribute */
    id: string;
    /** The name of the unit attribute */
    name: string;
    /** Description of unit attribute */
    description?: string;
  };
  UnitCreatedModel: {
    /** The unit id */
    id: string;
  };
  UnitGroupCreatedModel: {
    /** The unit group id */
    id: string;
  };
  UnitGroupItemModel: {
    /** The unit group id */
    id: string;
    /** The code for the unit group that can be shown in reports and table views */
    code: string;
    /** The name for the unit group */
    name: string;
    /** The description for the unit group */
    description: string;
    /** Number of units in this group */
    memberCount: number;
    /** Maximum number of persons for the unit group */
    maxPersons?: number;
    /** The unit group rank */
    rank?: number;
    /** The unit group type */
    type: "BedRoom" | "MeetingRoom" | "EventSpace" | "ParkingLot" | "Other";
    property: definitions["EmbeddedPropertyModel"];
    /** The list of connected unit groups this unit group is composed of */
    connectedUnitGroups?: definitions["ConnectedUnitGroupModel"][];
  };
  UnitGroupListModel: {
    /** List of unit groups */
    unitGroups: definitions["UnitGroupItemModel"][];
    /** Total count of items */
    count: number;
  };
  UnitGroupModel: {
    /** The unit group id */
    id: string;
    /** The code for the unit group that can be shown in reports and table views */
    code: string;
    property: definitions["EmbeddedPropertyModel"];
    /** The name for the unit group */
    name: { [key: string]: string };
    /** Number of units in this group */
    memberCount: number;
    /** The description for the unit group */
    description: { [key: string]: string };
    /** Maximum number of persons for the unit group */
    maxPersons: number;
    /** The unit group rank */
    rank?: number;
    /** The unit group type */
    type: "BedRoom" | "MeetingRoom" | "EventSpace" | "ParkingLot" | "Other";
    /** The list of connected unit groups this unit group is composed of */
    connectedUnitGroups?: definitions["ConnectedUnitGroupModel"][];
  };
  UnitItemMaintenanceModel: {
    /** The id for the scheduled maintenance */
    id: string;
    /**
     * The type of maintenance that is planned for the unit. A small repair (OutOfService),
     * a bigger disfunction that does not allow to sell the unit (OutOfOrder) or is it
     * even under construction and should reduce the house count (OutOfInventory)
     */
    type: "OutOfService" | "OutOfOrder" | "OutOfInventory";
  };
  UnitItemModel: {
    /** The unit id */
    id: string;
    /** The name for the unit */
    name: string;
    /** The description for the unit */
    description: string;
    property: definitions["EmbeddedPropertyModel"];
    unitGroup?: definitions["EmbeddedUnitGroupModel"];
    connectingUnit?: definitions["EmbeddedUnitModel"];
    status: definitions["UnitItemStatusModel"];
    /** Maximum number of persons for the unit */
    maxPersons: number;
    /** Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a> */
    created: string;
    /** Collection of user defined attributes of unit */
    attributes?: definitions["UnitAttributeModel"][];
    /** Collection of connected units */
    connectedUnits?: definitions["ConnectedUnitModel"][];
  };
  UnitItemStatusModel: {
    isOccupied: boolean;
    condition: "Clean" | "CleanToBeInspected" | "Dirty";
    maintenance?: definitions["UnitItemMaintenanceModel"];
  };
  UnitListModel: {
    /** List of units */
    units: definitions["UnitItemModel"][];
    /** Total count of items */
    count: number;
  };
  UnitMaintenanceModel: {
    /** The id for the scheduled maintenance */
    id: string;
    /** Date and time the scheduled maintenance window starts<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a> */
    from: string;
    /** Date and time the scheduled maintenance window ends<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a> */
    to: string;
    /**
     * The type of maintenance that is planned for the unit. A small repair (OutOfService),
     * a bigger disfunction that does not allow to sell the unit (OutOfOrder) or is it
     * even under construction and should reduce the house count (OutOfInventory)
     */
    type: "OutOfService" | "OutOfOrder" | "OutOfInventory";
    /** The description text for the maintenance */
    description?: string;
  };
  UnitModel: {
    /** The unit id */
    id: string;
    /** The name for the unit */
    name: string;
    /** The description for the unit */
    description: { [key: string]: string };
    property: definitions["EmbeddedPropertyModel"];
    unitGroup?: definitions["EmbeddedUnitGroupModel"];
    connectingUnit?: definitions["EmbeddedUnitModel"];
    status: definitions["UnitStatusModel"];
    /** Maximum number of persons for the unit */
    maxPersons: number;
    /** Date of creation<br />A date and time (without fractional second part) in UTC or with UTC offset as defined in <a href="https://en.wikipedia.org/wiki/ISO_8601">ISO8601:2004</a> */
    created: string;
    /** Collection of user defined attributes of unit */
    attributes?: definitions["UnitAttributeModel"][];
    /** Collection of connected units */
    connectedUnits?: definitions["ConnectedUnitModel"][];
  };
  UnitStatusModel: {
    isOccupied: boolean;
    condition: "Clean" | "CleanToBeInspected" | "Dirty";
    maintenance?: definitions["UnitMaintenanceModel"];
  };
}

export interface operations {
  /** Get the list of properties.<br>You need to be authorized (no particular scope required) */
  InventoryPropertiesGet: {
    parameters: {
      query: {
        /** Filter result by property status */
        status?: ("Test" | "Live")[];
        /** Include archived properties in the result. If not set, or set to false, it only returns non-archived properties */
        includeArchived?: boolean;
        /** Filter result by country code */
        countryCode?: string[];
        /** Page number, 1-based. Default value is 1 (if this is not set or not positive). Results in 204 if there are no items on that page. */
        pageNumber?: number;
        /** Page size. If this is not set or not positive, the pageNumber is ignored and all items are returned. */
        pageSize?: number;
        /** List of all embedded resources that should be expanded in the response. Possible values are: actions. All other values will be silently ignored. */
        expand?: "actions"[];
      };
    };
    responses: {
      /** Return all properties. */
      200: {
        schema: definitions["PropertyListModel"];
      };
      /** There are no properties found. */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Use this call to create a new property.<br>You must have at least one of these scopes: 'properties.create, setup.manage'. */
  InventoryPropertiesPost: {
    parameters: {
      header: {
        /**
         * Unique key for safely retrying requests without accidentally performing the same operation twice.
         * We'll always send back the same response for requests made with the same key,
         * and keys can't be reused with different request parameters. Keys expire after 24 hours.
         */
        "Idempotency-Key"?: string;
      };
      body: {
        /** The definition of the property. */
        body: definitions["CreatePropertyModel"];
      };
    };
    responses: {
      /** Creation of the new property was successful. */
      201: {
        headers: {};
        schema: definitions["PropertyCreatedModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Return total count of properties<br>You need to be authorized (no particular scope required) */
  InventoryProperties$countGet: {
    responses: {
      /** Success */
      200: {
        schema: definitions["CountModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Get a property by id.<br>You need to be authorized (no particular scope required) */
  InventoryPropertiesByIdGet: {
    parameters: {
      path: {
        /** The id of the property. */
        id: string;
      };
      query: {
        /** 'all' or comma separated list of two-letter language codes (ISO Alpha-2) */
        languages?: string[];
        /** List of all embedded resources that should be expanded in the response. Possible values are: actions. All other values will be silently ignored. */
        expand?: "actions"[];
      };
    };
    responses: {
      /** Return all the property data. */
      200: {
        schema: definitions["PropertyModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Check if a property exists by id.<br>You need to be authorized (no particular scope required) */
  InventoryPropertiesByIdHead: {
    parameters: {
      path: {
        /** The id of the property. */
        id: string;
      };
    };
    responses: {
      /** The property exists. */
      200: unknown;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Here's a list of allowed operations:
   * - Replace Name
   * - Add, replace and remove Description
   * - Replace CompanyName
   * - Add, replace and remove ManagingDirectors
   * - Replace CommercialRegisterEntry
   * - Replace TaxId
   * - Replace Location
   * - Add, replace and remove BankAccount
   * - Replace PaymentTerms
   * - Set IsTemplate<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.
   */
  InventoryPropertiesByIdPatch: {
    parameters: {
      path: {
        /** The id of the property. */
        id: string;
      };
      body: {
        /** Define the list of operations to be applied to the resource. Learn more about JSON Patch here: http://jsonpatch.com/. */
        body: definitions["Operation"][];
      };
    };
    responses: {
      /** Success */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Use this call to clone a specific property.
   * This operation creates a new property with inventory and rate plans from the specified property.<br>You must have at least one of these scopes: 'properties.create, setup.manage'.
   */
  "InventoryProperty-actionsByIdClonePost": {
    parameters: {
      path: {
        /** The id of the property. */
        id: string;
      };
      header: {
        /**
         * Unique key for safely retrying requests without accidentally performing the same operation twice.
         * We'll always send back the same response for requests made with the same key,
         * and keys can't be reused with different request parameters. Keys expire after 24 hours.
         */
        "Idempotency-Key"?: string;
      };
      body: {
        /** The definition of the property. */
        body: definitions["CreatePropertyModel"];
      };
    };
    responses: {
      /** Cloning of the existing property was successful. */
      201: {
        headers: {};
        schema: definitions["PropertyCreatedModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Use this endpoint to archive an existing live property
   * This operation set the IsArchived flag to true<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.
   */
  "InventoryProperty-actionsByIdArchivePut": {
    parameters: {
      path: {
        /** The id of the property */
        id: string;
      };
    };
    responses: {
      /** No Content */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Use this endpoint to move an existing test property to live
   * This operation changes the property status to 'Live'<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.
   */
  "InventoryProperty-actionsByIdSet-livePut": {
    parameters: {
      path: {
        /** The id of the property */
        id: string;
      };
    };
    responses: {
      /** No Content */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Use this endpoint to delete all transactional data related to some test property
   * This operation deletes all transactional data related to the specified property. The property must be in 'Test' status.<br>You must have at least one of these scopes: 'properties.manage, setup.manage'.
   */
  "InventoryProperty-actionsByIdResetPut": {
    parameters: {
      path: {
        /** The id of the property */
        id: string;
      };
    };
    responses: {
      /** No Content */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Returns a list of ISO country codes that could be used to create properties.<br>You need to be authorized (no particular scope required) */
  InventoryTypesCountriesGet: {
    responses: {
      /** Success. */
      200: {
        schema: definitions["CountryListModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Get a unit by id.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'. */
  InventoryUnitsByIdGet: {
    parameters: {
      path: {
        /** The id of the unit. */
        id: string;
      };
      query: {
        /** 'all' or comma separated list of two-letter language codes (ISO Alpha-2) */
        languages?: string[];
        /** List of all embedded resources that should be expanded in the response. Possible values are: property, unitGroup, connectedUnits. All other values will be silently ignored. */
        expand?: ("property" | "unitGroup" | "connectedUnits")[];
      };
    };
    responses: {
      /** Return all the unit data. */
      200: {
        schema: definitions["UnitModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Use this call to delete a unit.<br>You must have at least one of these scopes: 'units.delete, setup.manage'. */
  InventoryUnitsByIdDelete: {
    parameters: {
      path: {
        /** The id of the unit. */
        id: string;
      };
    };
    responses: {
      /** Deletion of the unit was successful. */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Check if a unit exists by id.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'. */
  InventoryUnitsByIdHead: {
    parameters: {
      path: {
        /** The id of the unit. */
        id: string;
      };
    };
    responses: {
      /** The unit exists. */
      200: unknown;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Here's a list of allowed operations:
   * - Set unit condition
   * - Set unit description
   * - Set unit name
   * - Set unit unitGroupId
   * - Set unit maxPersons
   * - Add unit attribute
   * - Remove unit attribute<br>You must have at least one of these scopes: 'units.manage, setup.manage'.
   */
  InventoryUnitsByIdPatch: {
    parameters: {
      path: {
        /** The id of the unit. */
        id: string;
      };
      body: {
        /** Define the list of operations to be applied to the resource. Learn more about JSON Patch here: http://jsonpatch.com/. */
        body: definitions["Operation"][];
      };
    };
    responses: {
      /** Success */
      200: unknown;
      /** The unit was successfully modified. */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Get the list of units.<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'. */
  InventoryUnitsGet: {
    parameters: {
      query: {
        /** Return units for specific property */
        propertyId?: string;
        /** Return units for the specific unit group - <b>DEPRECATED: This property will be removed 20.04.2022. Use `UnitGroupIds` instead</b> */
        unitGroupId?: string;
        /** Return units with the specific unit groups */
        unitGroupIds?: string[];
        /** Return units with the specific unit attributes */
        unitAttributeIds?: string[];
        /** Return only occupied or vacant units */
        isOccupied?: boolean;
        /** Return units with the specific maintenance type */
        maintenanceType?: "OutOfService" | "OutOfOrder" | "OutOfInventory";
        /** Return units with a specific condition */
        condition?: "Clean" | "CleanToBeInspected" | "Dirty";
        /** This will filter all units where the provided text is contained in the unit name. The search is case insensitive. */
        textSearch?: string;
        /** Page number, 1-based. Default value is 1 (if this is not set or not positive). Results in 204 if there are no items on that page. */
        pageNumber?: number;
        /** Page size. If this is not set or not positive, the pageNumber is ignored and all items are returned. */
        pageSize?: number;
        /** List of all embedded resources that should be expanded in the response. Possible values are: property, unitGroup, connectedUnits. All other values will be silently ignored. */
        expand?: ("property" | "unitGroup" | "connectedUnits")[];
      };
    };
    responses: {
      /** Return all units. */
      200: {
        schema: definitions["UnitListModel"];
      };
      /** No units were found. */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Use this call to create a new unit.<br>You must have at least one of these scopes: 'units.create, setup.manage'. */
  InventoryUnitsPost: {
    parameters: {
      header: {
        /**
         * Unique key for safely retrying requests without accidentally performing the same operation twice.
         * We'll always send back the same response for requests made with the same key,
         * and keys can't be reused with different request parameters. Keys expire after 24 hours.
         */
        "Idempotency-Key"?: string;
      };
      body: {
        /** The definition of the unit. */
        body: definitions["CreateUnitModel"];
      };
    };
    responses: {
      /** Creation of the new unit was successful. */
      201: {
        headers: {};
        schema: definitions["UnitCreatedModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Here's a list of allowed operations:
   * - Set unit condition
   * - Set unit description
   * - Set unit name
   * - Set unit unitGroupId
   * - Set unit maxPersons
   * - Add unit attribute
   * - Remove unit attribute<br>You must have at least one of these scopes: 'units.manage, setup.manage'.
   */
  InventoryUnitsPatch: {
    parameters: {
      query: {
        unitIds: string[];
      };
      body: {
        /** Define the list of operations to be applied to the resource. Learn more about JSON Patch here: http://jsonpatch.com/. */
        body: definitions["Operation"][];
      };
    };
    responses: {
      /** Units were successfully modified. */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Returns number of units matching the filter criteria<br>You must have at least one of these scopes: 'units.read, setup.read, setup.manage'. */
  InventoryUnits$countGet: {
    parameters: {
      query: {
        /** Return units for specific property */
        propertyId?: string;
        /** Return units for the specific unit group - <b>DEPRECATED: This property will be removed 20.04.2022. Use `UnitGroupIds` instead</b> */
        unitGroupId?: string;
        /** Return units with the specific unit groups */
        unitGroupIds?: string[];
        /** Return units with the specific unit attributes */
        unitAttributeIds?: string[];
        /** Return only occupied or vacant units */
        isOccupied?: boolean;
        /** Return units with the specific maintenance type */
        maintenanceType?: "OutOfService" | "OutOfOrder" | "OutOfInventory";
        /** Return units with a specific condition */
        condition?: "Clean" | "CleanToBeInspected" | "Dirty";
        /** This will filter all units where the provided text is contained in the unit name. The search is case insensitive. */
        textSearch?: string;
      };
    };
    responses: {
      /** Success */
      200: {
        schema: definitions["CountModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Use this call to create multiple units, following a naming rule.<br>You must have at least one of these scopes: 'units.create, setup.manage'. */
  InventoryUnitsBulkPost: {
    parameters: {
      header: {
        /**
         * Unique key for safely retrying requests without accidentally performing the same operation twice.
         * We'll always send back the same response for requests made with the same key,
         * and keys can't be reused with different request parameters. Keys expire after 24 hours.
         */
        "Idempotency-Key"?: string;
      };
      body: {
        /** The definition of the units. */
        body: definitions["BulkCreateUnitsModel"];
      };
    };
    responses: {
      /** Success. */
      200: {
        schema: definitions["BulkUnitsCreatedModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Get unit attribute by id<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'. */
  "InventoryUnit-attributesByIdGet": {
    parameters: {
      path: {
        /** The id of the unit attribute */
        id: string;
      };
    };
    responses: {
      /** Returns unit attribute with specified id */
      200: {
        schema: definitions["UnitAttributeDefinitionModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Deletes unit attribute<br>You must have at least one of these scopes: 'unitattributes.delete, setup.manage'. */
  "InventoryUnit-attributesByIdDelete": {
    parameters: {
      path: {
        /** Id of unit attribute */
        id: string;
      };
    };
    responses: {
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Check if a unit attribute exists<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'. */
  "InventoryUnit-attributesByIdHead": {
    parameters: {
      path: {
        /** The id of the unit attribute. */
        id: string;
      };
    };
    responses: {
      /** The unit attribute exists. */
      200: unknown;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /**
   * Here's a list of allowed operations:
   * - Replace / Remove Description<br>You must have at least one of these scopes: 'unitattributes.manage, setup.manage'.
   */
  "InventoryUnit-attributesByIdPatch": {
    parameters: {
      path: {
        /** Id of unit attribute */
        id: string;
      };
      body: {
        /** Define the list of operations to be applied to the resource. Learn more about JSON Patch here: http://jsonpatch.com/. */
        body: definitions["Operation"][];
      };
    };
    responses: {
      /** No Content */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Get unit attribute list<br>You must have at least one of these scopes: 'unitattributes.read, setup.read, setup.manage'. */
  "InventoryUnit-attributesGet": {
    parameters: {
      query: {
        /** Page number, 1-based. Default value is 1 (if this is not set or not positive). Results in 204 if there are no items on that page. */
        pageNumber?: number;
        /** Page size. If this is not set or not positive, the pageNumber is ignored and all items are returned. */
        pageSize?: number;
      };
    };
    responses: {
      /** Returns unit attribute list for given account */
      200: {
        schema: definitions["UnitAttributeDefinitionListModel"];
      };
      /** No unit attributes present for given account */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Use this call to create a new unit attribute.<br>You must have at least one of these scopes: 'unitattributes.create, setup.manage'. */
  "InventoryUnit-attributesPost": {
    parameters: {
      header: {
        /**
         * Unique key for safely retrying requests without accidentally performing the same operation twice.
         * We'll always send back the same response for requests made with the same key,
         * and keys can't be reused with different request parameters. Keys expire after 24 hours.
         */
        "Idempotency-Key"?: string;
      };
      body: {
        /** The unit attribute. */
        body: definitions["CreateUnitAttributeDefinitionModel"];
      };
    };
    responses: {
      /** Creation of the new unit attribute was successful. */
      201: {
        headers: {};
        schema: definitions["UnitAttributeDefinitionCreatedModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Get the list of unit groups.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'. */
  "InventoryUnit-groupsGet": {
    parameters: {
      query: {
        /** Return unit groups for specific property */
        propertyId?: string;
        unitGroupTypes?: (
          | "BedRoom"
          | "MeetingRoom"
          | "EventSpace"
          | "ParkingLot"
          | "Other"
        )[];
        /** Page number, 1-based. Default value is 1 (if this is not set or not positive). Results in 204 if there are no items on that page. */
        pageNumber?: number;
        /** Page size. If this is not set or not positive, the pageNumber is ignored and all items are returned. */
        pageSize?: number;
        /** List of all embedded resources that should be expanded in the response. Possible values are: property, connectedUnitGroups. All other values will be silently ignored. */
        expand?: ("property" | "connectedUnitGroups")[];
      };
    };
    responses: {
      /** Return all unit groups. */
      200: {
        schema: definitions["UnitGroupListModel"];
      };
      /** There are no unit groups found. */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Use this call to create a new unit group.<br>You must have at least one of these scopes: 'unitgroups.create, setup.manage'. */
  "InventoryUnit-groupsPost": {
    parameters: {
      header: {
        /**
         * Unique key for safely retrying requests without accidentally performing the same operation twice.
         * We'll always send back the same response for requests made with the same key,
         * and keys can't be reused with different request parameters. Keys expire after 24 hours.
         */
        "Idempotency-Key"?: string;
      };
      body: {
        /** The definition of the unit group. */
        body: definitions["CreateUnitGroupModel"];
      };
    };
    responses: {
      /** Creation of the new unit group was successful. */
      201: {
        headers: {};
        schema: definitions["UnitGroupCreatedModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Returns number of unit groups matching the filter criteria<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'. */
  "InventoryUnit-groups$countGet": {
    parameters: {
      query: {
        /** Return unit groups for specific property */
        propertyId?: string;
        unitGroupTypes?: (
          | "BedRoom"
          | "MeetingRoom"
          | "EventSpace"
          | "ParkingLot"
          | "Other"
        )[];
      };
    };
    responses: {
      /** Success */
      200: {
        schema: definitions["CountModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Get a unit group by id.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'. */
  "InventoryUnit-groupsByIdGet": {
    parameters: {
      path: {
        /** The id of the unit group. */
        id: string;
      };
      query: {
        /** 'all' or comma separated list of two-letter language codes (ISO Alpha-2) */
        languages?: string[];
        /** List of all embedded resources that should be expanded in the response. Possible values are: property, connectedUnitGroups. All other values will be silently ignored. */
        expand?: ("property" | "connectedUnitGroups")[];
      };
    };
    responses: {
      /** Return all the unit group data. */
      200: {
        schema: definitions["UnitGroupModel"];
      };
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Use this call to modify a unit group.<br>You must have at least one of these scopes: 'unitgroups.manage, setup.manage'. */
  "InventoryUnit-groupsByIdPut": {
    parameters: {
      path: {
        /** The id of the unit group. */
        id: string;
      };
      body: {
        /** The definition of the unit group. */
        body: definitions["ReplaceUnitGroupModel"];
      };
    };
    responses: {
      /** Success */
      200: unknown;
      /** Replace of the unit group was successful. */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Unsupported media type. */
      415: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Use this call to delete a unit group.<br>You must have at least one of these scopes: 'unitgroups.delete, setup.manage'. */
  "InventoryUnit-groupsByIdDelete": {
    parameters: {
      path: {
        /** The id of the unit group. */
        id: string;
      };
    };
    responses: {
      /** Deletion of the unit group was successful. */
      204: never;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** Validation errors in the request body or query params. */
      422: {
        schema: definitions["MessageItemCollection"];
      };
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
  /** Check if a unit group exists by id.<br>You must have at least one of these scopes: 'unitgroups.read, setup.read, setup.manage'. */
  "InventoryUnit-groupsByIdHead": {
    parameters: {
      path: {
        /** The id of the unit group. */
        id: string;
      };
    };
    responses: {
      /** The unit group exists. */
      200: unknown;
      /** Bad request. */
      400: unknown;
      /** You are unauthorized. */
      401: unknown;
      /** Forbidden. */
      403: unknown;
      /** The Request-URI could not be found. */
      404: unknown;
      /** An unexpected error occurred. */
      500: unknown;
      /** The server is currently unavailable. Please try later. */
      503: unknown;
    };
  };
}

export interface external {}
